// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhiteLagoon.Infrastructure.Data;

#nullable disable

namespace WhiteLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214065410_seedVillatoDb")]
    partial class seedVillatoDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MeterSquared")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Occupancy")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 14, 6, 54, 10, 312, DateTimeKind.Utc).AddTicks(3173),
                            Description = "A serene coastal villa with panoramic ocean views and a private infinity pool.",
                            ImageUrl = "https://placehold.co/600x400/EEE/31343C",
                            MeterSquared = 220,
                            Name = "Azure Haven",
                            Occupancy = 6,
                            Price = 450.0,
                            UpdatedAt = new DateTime(2025, 12, 14, 6, 54, 10, 312, DateTimeKind.Utc).AddTicks(3383)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 14, 6, 54, 10, 312, DateTimeKind.Utc).AddTicks(3612),
                            Description = "Nestled in the mountains, this rustic-chic villa offers fireplace warmth and forest trails.",
                            ImageUrl = "https://placehold.co/600x400/EEE/31343C",
                            MeterSquared = 180,
                            Name = "Pinecrest Lodge",
                            Occupancy = 4,
                            Price = 320.5,
                            UpdatedAt = new DateTime(2025, 12, 14, 6, 54, 10, 312, DateTimeKind.Utc).AddTicks(3612)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 14, 6, 54, 10, 312, DateTimeKind.Utc).AddTicks(3614),
                            Description = "Luxury meets comfort in this sun-drenched villa with tropical gardens and outdoor kitchen.",
                            ImageUrl = "https://placehold.co/600x400/EEE/31343C",
                            MeterSquared = 260,
                            Name = "Sunny Palms Estate",
                            Occupancy = 8,
                            Price = 580.75,
                            UpdatedAt = new DateTime(2025, 12, 14, 6, 54, 10, 312, DateTimeKind.Utc).AddTicks(3614)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 14, 6, 54, 10, 312, DateTimeKind.Utc).AddTicks(3616),
                            Description = "Modern city-center villa with floor-to-ceiling windows and rooftop terrace access.",
                            ImageUrl = "https://placehold.co/600x400/EEE/31343C",
                            MeterSquared = 140,
                            Name = "Urban Loft Retreat",
                            Occupancy = 3,
                            Price = 290.0,
                            UpdatedAt = new DateTime(2025, 12, 14, 6, 54, 10, 312, DateTimeKind.Utc).AddTicks(3616)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 14, 6, 54, 10, 312, DateTimeKind.Utc).AddTicks(3618),
                            Description = "Tranquil lakeside property with canoe dock, fire pit, and cozy interior design.",
                            ImageUrl = "https://placehold.co/600x400/EEE/31343C",
                            MeterSquared = 200,
                            Name = "Lakeside Serenity",
                            Occupancy = 5,
                            Price = 410.25,
                            UpdatedAt = new DateTime(2025, 12, 14, 6, 54, 10, 312, DateTimeKind.Utc).AddTicks(3618)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
