// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhiteLagoon.Infrastructure.Data;

#nullable disable

namespace WhiteLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214104635_addVillaNumbersAndSeed")]
    partial class addVillaNumbersAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MeterSquared")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Occupancy")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 14, 10, 46, 34, 383, DateTimeKind.Unspecified).AddTicks(2031), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A serene coastal villa with panoramic ocean views and a private infinity pool.",
                            ImageUrl = "https://placehold.co/600x400/EEE/31343C",
                            MeterSquared = 220,
                            Name = "Azure Haven",
                            Occupancy = 6,
                            Price = 450.0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 14, 10, 46, 34, 383, DateTimeKind.Unspecified).AddTicks(2908), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 14, 10, 46, 34, 383, DateTimeKind.Unspecified).AddTicks(3155), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Nestled in the mountains, this rustic-chic villa offers fireplace warmth and forest trails.",
                            ImageUrl = "https://placehold.co/600x400/EEE/31343C",
                            MeterSquared = 180,
                            Name = "Pinecrest Lodge",
                            Occupancy = 4,
                            Price = 320.5,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 14, 10, 46, 34, 383, DateTimeKind.Unspecified).AddTicks(3156), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 14, 10, 46, 34, 383, DateTimeKind.Unspecified).AddTicks(3158), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Luxury meets comfort in this sun-drenched villa with tropical gardens and outdoor kitchen.",
                            ImageUrl = "https://placehold.co/600x400/EEE/31343C",
                            MeterSquared = 260,
                            Name = "Sunny Palms Estate",
                            Occupancy = 8,
                            Price = 580.75,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 14, 10, 46, 34, 383, DateTimeKind.Unspecified).AddTicks(3158), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 14, 10, 46, 34, 383, DateTimeKind.Unspecified).AddTicks(3160), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Modern city-center villa with floor-to-ceiling windows and rooftop terrace access.",
                            ImageUrl = "https://placehold.co/600x400/EEE/31343C",
                            MeterSquared = 140,
                            Name = "Urban Loft Retreat",
                            Occupancy = 3,
                            Price = 290.0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 14, 10, 46, 34, 383, DateTimeKind.Unspecified).AddTicks(3161), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 14, 10, 46, 34, 383, DateTimeKind.Unspecified).AddTicks(3162), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tranquil lakeside property with canoe dock, fire pit, and cozy interior design.",
                            ImageUrl = "https://placehold.co/600x400/EEE/31343C",
                            MeterSquared = 200,
                            Name = "Lakeside Serenity",
                            Occupancy = 5,
                            Price = 410.25,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 14, 10, 46, 34, 383, DateTimeKind.Unspecified).AddTicks(3163), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("Villa_Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Villa_Number"));

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("text");

                    b.Property<int>("VillaId")
                        .HasColumnType("integer");

                    b.HasKey("Villa_Number");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumber");

                    b.HasData(
                        new
                        {
                            Villa_Number = 101,
                            SpecialDetails = "Ocean view balcony with private hot tub",
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 102,
                            SpecialDetails = "Ground floor access, wheelchair accessible",
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 103,
                            SpecialDetails = "Rooftop terrace with telescope for stargazing",
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 201,
                            SpecialDetails = "Forest-facing room with suspended fireplace",
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 202,
                            SpecialDetails = "Private sauna and cold plunge pool access",
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 203,
                            SpecialDetails = "Artist's studio with natural lighting",
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 301,
                            SpecialDetails = "Infinity pool edge overlooking tropical gardens",
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 302,
                            SpecialDetails = "Chef's kitchenette with premium appliances",
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 303,
                            SpecialDetails = "Glass-walled bedroom with jungle canopy views",
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 401,
                            SpecialDetails = "Soundproofed media room with 4K projector",
                            VillaId = 4
                        },
                        new
                        {
                            Villa_Number = 402,
                            SpecialDetails = "Executive workspace with ergonomic setup",
                            VillaId = 4
                        },
                        new
                        {
                            Villa_Number = 403,
                            SpecialDetails = "Penthouse suite with 360° city skyline views",
                            VillaId = 4
                        },
                        new
                        {
                            Villa_Number = 501,
                            SpecialDetails = "Lakeside deck with private canoe dock",
                            VillaId = 5
                        },
                        new
                        {
                            Villa_Number = 502,
                            SpecialDetails = "Indoor/outdoor fireplace with lakeside seating",
                            VillaId = 5
                        },
                        new
                        {
                            Villa_Number = 503,
                            SpecialDetails = "Botanical garden conservatory with breakfast nook",
                            VillaId = 5
                        });
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("WhiteLagoon.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
