// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhiteLagoon.Infrastructure.Data;

#nullable disable

namespace WhiteLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220114330_addApplicationUserAndUpdateVillaDates")]
    partial class addApplicationUserAndUpdateVillaDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VillaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VillaId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Stunning infinity pool overlooking the ocean with automatic cleaning system",
                            Name = "Private Infinity Pool",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Private stairway leading directly to the pristine white sand beach",
                            Name = "Beach Access",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Spacious balcony with panoramic ocean views and comfortable seating",
                            Name = "Ocean View Balcony",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Luxurious outdoor rainfall shower surrounded by tropical plants",
                            Name = "Outdoor Shower",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Integrated smart home controls for lighting, climate, and entertainment",
                            Name = "Smart Home System",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Authentic stone fireplace with wood-burning capability and heated mantel",
                            Name = "Stone Fireplace",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Direct access to private hiking trails through scenic mountain forests",
                            Name = "Mountain Hiking Trails",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Premium hot tub with hydrotherapy jets and mountain view",
                            Name = "Hot Tub",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Traditional cedar wood sauna with aroma therapy options",
                            Name = "Wood Sauna",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "Radiant floor heating throughout the villa for cozy winter comfort",
                            Name = "Heated Floors",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "Professionally landscaped gardens with exotic plants and water features",
                            Name = "Tropical Gardens",
                            VillaId = 3
                        },
                        new
                        {
                            Id = 12,
                            Description = "Fully equipped outdoor kitchen with BBQ grill, sink, and bar seating",
                            Name = "Outdoor Kitchen",
                            VillaId = 3
                        },
                        new
                        {
                            Id = 13,
                            Description = "Large swimming pool with swim-up bar and underwater lighting",
                            Name = "Swimming Pool",
                            VillaId = 3
                        },
                        new
                        {
                            Id = 14,
                            Description = "Relaxing hammock area under palm trees with shade sails",
                            Name = "Hammock Area",
                            VillaId = 3
                        },
                        new
                        {
                            Id = 15,
                            Description = "Authentic tiki bar with thatched roof and tropical drink service",
                            Name = "Tiki Bar",
                            VillaId = 3
                        },
                        new
                        {
                            Id = 16,
                            Description = "Exclusive rooftop terrace with city views and lounge furniture",
                            Name = "Rooftop Terrace",
                            VillaId = 4
                        },
                        new
                        {
                            Id = 17,
                            Description = "Advanced smart home system with voice control and automation",
                            Name = "Smart Home System",
                            VillaId = 4
                        },
                        new
                        {
                            Id = 18,
                            Description = "Floor-to-ceiling windows offering breathtaking city skyline views",
                            Name = "City Skyline Views",
                            VillaId = 4
                        },
                        new
                        {
                            Id = 19,
                            Description = "Gigabit fiber internet with dedicated Wi-Fi 6 access points",
                            Name = "High-Speed Internet",
                            VillaId = 4
                        },
                        new
                        {
                            Id = 20,
                            Description = "24/7 concierge service for restaurant reservations and city experiences",
                            Name = "Concierge Service",
                            VillaId = 4
                        },
                        new
                        {
                            Id = 21,
                            Description = "Private wooden dock extending into the lake with seating area",
                            Name = "Private Dock",
                            VillaId = 5
                        },
                        new
                        {
                            Id = 22,
                            Description = "Stone fire pit with comfortable seating for lakeside evenings",
                            Name = "Fire Pit",
                            VillaId = 5
                        },
                        new
                        {
                            Id = 23,
                            Description = "Two-person canoe and two kayaks available for lake exploration",
                            Name = "Canoe/Kayak Access",
                            VillaId = 5
                        },
                        new
                        {
                            Id = 24,
                            Description = "Large covered patio with dining area and lake views",
                            Name = "Lakeside Patio",
                            VillaId = 5
                        },
                        new
                        {
                            Id = 25,
                            Description = "Professionally maintained botanical garden with walking paths",
                            Name = "Botanical Garden",
                            VillaId = 5
                        });
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MeterSquared")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Occupancy")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 20, 11, 43, 29, 705, DateTimeKind.Unspecified).AddTicks(1378), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A serene coastal villa with panoramic ocean views and a private infinity pool.",
                            ImageUrl = "https://placehold.co/600x400/EEE/31343C",
                            MeterSquared = 220,
                            Name = "Azure Haven",
                            Occupancy = 6,
                            Price = 450.0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 20, 11, 43, 29, 705, DateTimeKind.Unspecified).AddTicks(2194), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 20, 11, 43, 29, 705, DateTimeKind.Unspecified).AddTicks(2602), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Nestled in the mountains, this rustic-chic villa offers fireplace warmth and forest trails.",
                            ImageUrl = "https://placehold.co/600x400/EEE/31343C",
                            MeterSquared = 180,
                            Name = "Pinecrest Lodge",
                            Occupancy = 4,
                            Price = 320.5,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 20, 11, 43, 29, 705, DateTimeKind.Unspecified).AddTicks(2603), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 20, 11, 43, 29, 705, DateTimeKind.Unspecified).AddTicks(2605), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Luxury meets comfort in this sun-drenched villa with tropical gardens and outdoor kitchen.",
                            ImageUrl = "https://placehold.co/600x400/EEE/31343C",
                            MeterSquared = 260,
                            Name = "Sunny Palms Estate",
                            Occupancy = 8,
                            Price = 580.75,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 20, 11, 43, 29, 705, DateTimeKind.Unspecified).AddTicks(2606), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 20, 11, 43, 29, 705, DateTimeKind.Unspecified).AddTicks(2607), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Modern city-center villa with floor-to-ceiling windows and rooftop terrace access.",
                            ImageUrl = "https://placehold.co/600x400/EEE/31343C",
                            MeterSquared = 140,
                            Name = "Urban Loft Retreat",
                            Occupancy = 3,
                            Price = 290.0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 20, 11, 43, 29, 705, DateTimeKind.Unspecified).AddTicks(2608), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 20, 11, 43, 29, 705, DateTimeKind.Unspecified).AddTicks(2609), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tranquil lakeside property with canoe dock, fire pit, and cozy interior design.",
                            ImageUrl = "https://placehold.co/600x400/EEE/31343C",
                            MeterSquared = 200,
                            Name = "Lakeside Serenity",
                            Occupancy = 5,
                            Price = 410.25,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 20, 11, 43, 29, 705, DateTimeKind.Unspecified).AddTicks(2610), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("Villa_Number")
                        .HasColumnType("integer");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("text");

                    b.Property<int>("VillaId")
                        .HasColumnType("integer");

                    b.HasKey("Villa_Number");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            Villa_Number = 101,
                            SpecialDetails = "Ocean view balcony with private hot tub",
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 102,
                            SpecialDetails = "Ground floor access, wheelchair accessible",
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 103,
                            SpecialDetails = "Rooftop terrace with telescope for stargazing",
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 201,
                            SpecialDetails = "Forest-facing room with suspended fireplace",
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 202,
                            SpecialDetails = "Private sauna and cold plunge pool access",
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 203,
                            SpecialDetails = "Artist's studio with natural lighting",
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 301,
                            SpecialDetails = "Infinity pool edge overlooking tropical gardens",
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 302,
                            SpecialDetails = "Chef's kitchenette with premium appliances",
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 303,
                            SpecialDetails = "Glass-walled bedroom with jungle canopy views",
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 401,
                            SpecialDetails = "Soundproofed media room with 4K projector",
                            VillaId = 4
                        },
                        new
                        {
                            Villa_Number = 402,
                            SpecialDetails = "Executive workspace with ergonomic setup",
                            VillaId = 4
                        },
                        new
                        {
                            Villa_Number = 403,
                            SpecialDetails = "Penthouse suite with 360° city skyline views",
                            VillaId = 4
                        },
                        new
                        {
                            Villa_Number = 501,
                            SpecialDetails = "Lakeside deck with private canoe dock",
                            VillaId = 5
                        },
                        new
                        {
                            Villa_Number = 502,
                            SpecialDetails = "Indoor/outdoor fireplace with lakeside seating",
                            VillaId = 5
                        },
                        new
                        {
                            Villa_Number = 503,
                            SpecialDetails = "Botanical garden conservatory with breakfast nook",
                            VillaId = 5
                        });
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Amenity", b =>
                {
                    b.HasOne("WhiteLagoon.Domain.Entities.Villa", "Villa")
                        .WithMany("VillaAmenity")
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("WhiteLagoon.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Navigation("VillaAmenity");
                });
#pragma warning restore 612, 618
        }
    }
}
